### ISSUE TITLE
laskuttamattomuusasteessa ehkä häikkää

### ISSUE THREAD

**Issue by horttanainen** [timotm/hours-stat#4]
Tässä mun kesäkuu:
  ### Kesäkuu 2018 (17 arkipäivää, 1 arkipäiviin osuvaa vapaapäivää ja 16 työpäivää)
  Yhteensä 125.0 h kuukauden 120.0 työtunnista joista
    - laskutettavia 122.0 h, laskutusaste 101.7 %
       122.0	CENSORED
    - laskutettamattomia 3.0 h, laskuttamattomuusaste 2.5 %
       3.0	CENSORED

Eli laskuttamattomuusaste 2.5% vaikka laskutusaste yli 100%, jokin ei nyt täsmää. 

Voin korjata jos katsotte, että tässä on bugi

**Comment by timotm** [comment]
molemmat asteet (laskutus- ja laskuttamattomuus-) lasketaan kuukauden työtunneista. Koko laskuttamattomuusaste-ominaisuus ei ehkä ole niin vakavasti otettava juttu niin sanoisin kyllä WONTFIX tai WORKSFORME 🙃
